/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import { Contract, ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import { ContractEvent, Callback, TransactionObject, BlockType } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class OpenOracleMock extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  clone(): OpenOracleMock;
  methods: {
    data(
      arg0: string,
      arg1: string
    ): TransactionObject<{
      value: string;
      timestamp: string;
      0: string;
      1: string;
    }>;

    get(
      source: string,
      key: string
    ): TransactionObject<{
      0: string;
      1: string;
    }>;

    set(
      source: string,
      key: string,
      value: number | string,
      timestamp: number | string
    ): TransactionObject<void>;
  };
  events: {
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
